/* Generated by Trae Work
 * assets/app.js — English Library 在线只读版
 * 数据从同目录 data.json 加载（由管理员通过 admin.html 发布），访客仅可浏览、播放与下载
 */
(function () {
  'use strict';

  var TYPES = window.LIB_TYPES || [];
  var TYPE_MAP = {};
  TYPES.forEach(function (t) { TYPE_MAP[t.id] = t; });

  var STAGE_META = {
    junior: { name: '初中', cls: 'badge-stage-junior' },
    senior: { name: '高中', cls: 'badge-stage-senior' }
  };

  /* ================= 状态 ================= */
  var state = {
    items: [],
    stage: 'all',
    type: 'all',
    q: '',
    sort: 'newest'
  };

  /* ================= DOM 引用 ================= */
  function $(id) { return document.getElementById(id); }
  var grid         = $('grid');
  var searchInput  = $('searchInput');
  var stageFilter  = $('stageFilter');
  var typeFilter   = $('typeFilter');
  var sortSelect   = $('sortSelect');
  var resultCount  = $('resultCount');
  var toastEl      = $('toast');

  /* ================= 工具 ================= */
  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }
  function fmtSize(n) {
    if (!n) return '';
    if (n < 1024) return n + ' B';
    if (n < 1024 * 1024) return (n / 1024).toFixed(1) + ' KB';
    return (n / 1024 / 1024).toFixed(2) + ' MB';
  }
  function fmtDate(ts) {
    var d = new Date(ts);
    var p = function (x) { return x < 10 ? '0' + x : x; };
    return d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate());
  }
  function toast(msg, ms) {
    if (!toastEl) return;
    toastEl.textContent = msg;
    toastEl.classList.add('show');
    clearTimeout(toast._t);
    toast._t = setTimeout(function () { toastEl.classList.remove('show'); }, ms || 2200);
  }

  /* ================= 渲染 ================= */
  function renderStats() {
    var items = state.items;
    var n = items.length;
    var audio = 0, exam = 0, junior = 0, senior = 0;
    items.forEach(function (it) {
      if (it.type === 'audio') audio++;
      if (it.type === 'exam') exam++;
      if (it.stage === 'junior') junior++; else senior++;
    });
    $('statTotal').textContent = n;
    $('statAudio').textContent = audio;
    $('statExam').textContent = exam;
    $('statJunior').textContent = junior;
    $('statSenior').textContent = senior;
  }

  function renderTypeFilter() {
    var items = state.items;
    var html = '<button data-v="all" class="on">全部类型</button>';
    TYPES.forEach(function (t) {
      var c = items.filter(function (it) { return it.type === t.id; }).length;
      html += '<button data-v="' + t.id + '">' + t.name + '（' + c + '）</button>';
    });
    typeFilter.innerHTML = html;
    var cur = typeFilter.querySelector('[data-v="' + state.type + '"]');
    if (cur) {
      typeFilter.querySelectorAll('button').forEach(function (b) { b.classList.remove('on'); });
      cur.classList.add('on');
    }
    typeFilter.querySelectorAll('button').forEach(function (b) {
      b.addEventListener('click', function () {
        typeFilter.querySelectorAll('button').forEach(function (x) { x.classList.remove('on'); });
        b.classList.add('on');
        state.type = b.getAttribute('data-v');
        renderGrid();
      });
    });
  }

  function filterItems() {
    var q = state.q.trim().toLowerCase();
    var out = state.items.filter(function (it) {
      if (state.stage !== 'all' && it.stage !== state.stage) return false;
      if (state.type !== 'all' && it.type !== state.type) return false;
      if (q) {
        var hay = (it.name + ' ' + it.desc + ' ' + (it.tags || []).join(' ')).toLowerCase();
        if (hay.indexOf(q) === -1) return false;
      }
      return true;
    });
    out.sort(function (a, b) {
      if (state.sort === 'name') return a.name.localeCompare(b.name, 'zh');
      var da = a.createdAt || 0, db = b.createdAt || 0;
      return state.sort === 'oldest' ? da - db : db - da;
    });
    return out;
  }

  function cardAudioPlayer(it) {
    var s = it.src || {};
    if (s.kind === 'file' && s.mime && s.mime.indexOf('audio/') === 0 && s.data) {
      return '<audio controls preload="none" src="data:' + esc(s.mime) + ';base64,' + s.data + '" style="width:100%;height:34px"></audio>';
    }
    return '';
  }

  function cardActions(it) {
    var s = it.src || {};
    if (s.kind === 'file' && s.data) {
      return '<div class="card-actions"><a class="mini-btn open" href="#" data-act="open" data-id="' + it.id + '">⬇ 下载</a></div>';
    }
    if (s.kind === 'link' && s.data) {
      return '<div class="card-actions"><a class="mini-btn open" href="' + esc(s.data) + '" target="_blank" rel="noopener">↗ 打开</a></div>';
    }
    return '';
  }

  function renderGrid() {
    var list = filterItems();
    resultCount.textContent = '共 ' + list.length + ' 条结果';
    if (!list.length) {
      grid.innerHTML = '<div class="empty"><div class="big">🔍</div>没有找到匹配的资料<br>试试更换关键词或筛选条件</div>';
      return;
    }
    var html = '';
    list.forEach(function (it) {
      var t = TYPE_MAP[it.type] || TYPE_MAP.other;
      var st = STAGE_META[it.stage] || STAGE_META.junior;
      var s = it.src || {};
      var sizeTxt = s.kind === 'file' ? fmtSize(s.size) : (s.kind === 'link' ? '链接' : '');
      var tagsHtml = (it.tags || []).map(function (x) {
        return '<span class="tag">#' + esc(x) + '</span>';
      }).join('');

      html += '<div class="card">' +
        '<div class="card-top"><div class="card-ic" style="background:' + t.color + '">' + t.icon + '</div>' +
        '<div class="card-title">' + esc(it.name) + '</div></div>' +
        '<div class="card-badges">' +
        '<span class="badge ' + st.cls + '">' + st.name + '</span>' +
        '<span class="badge badge-type">' + t.name + '</span>' +
        '</div>' +
        (it.desc ? '<div class="card-desc">' + esc(it.desc) + '</div>' : '') +
        (tagsHtml ? '<div class="card-tags">' + tagsHtml + '</div>' : '') +
        cardAudioPlayer(it) +
        '<div class="card-meta"><span class="sz">' + sizeTxt + '</span><span>' + fmtDate(it.createdAt) + '</span></div>' +
        cardActions(it) +
        '</div>';
    });
    grid.innerHTML = html;
  }

  function renderAll() {
    renderStats();
    renderTypeFilter();
    renderGrid();
    if (window.renderCharts) window.renderCharts(state.items);
  }

  /* ================= 事件 ================= */
  searchInput.addEventListener('input', function () {
    state.q = searchInput.value;
    renderGrid();
  });

  stageFilter.addEventListener('click', function (e) {
    var b = e.target.closest('button');
    if (!b) return;
    stageFilter.querySelectorAll('button').forEach(function (x) { x.classList.remove('on'); });
    b.classList.add('on');
    state.stage = b.getAttribute('data-v');
    renderGrid();
  });

  sortSelect.addEventListener('change', function () {
    state.sort = sortSelect.value;
    renderGrid();
  });

  grid.addEventListener('click', function (e) {
    var btn = e.target.closest('[data-act]');
    if (!btn) return;
    if (btn.getAttribute('data-act') === 'open') e.preventDefault();
    var it = state.items.find(function (x) { return x.id === btn.getAttribute('data-id'); });
    if (!it) return;
    var s = it.src || {};
    if (s.kind === 'file' && s.data) {
      var a = document.createElement('a');
      a.href = 'data:' + (s.mime || 'application/octet-stream') + ';base64,' + s.data;
      a.download = s.name || it.name;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    }
  });

  /* ================= 数据加载 ================= */
  function loadData() {
    fetch('./data.json', { cache: 'no-cache' })
      .then(function (r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      })
      .then(function (arr) {
        if (!Array.isArray(arr)) throw new Error('数据格式错误');
        state.items = arr;
        renderAll();
      })
      .catch(function () {
        resultCount.textContent = '数据加载失败';
        grid.innerHTML = '<div class="empty"><div class="big">📡</div>资料数据加载失败<br>请确认网站已随仓库发布 data.json 文件，或稍后刷新重试</div>';
      });
  }

  loadData();
})();
