/* Generated by Trae Work
 * assets/charts.js — 资料统计图表（类型分布柱状图 + 学段分布环形图）
 * 暴露 window.LIB_TYPES（类型元数据）与 window.renderCharts(items)
 */
(function () {
  'use strict';

  // 类型元数据（与卡片渲染共用）
  var TYPE_META = [
    { id: 'audio',    name: '单词音频', color: '#2563eb', icon: '🔊' },
    { id: 'exam',     name: '试卷',     color: '#ef4444', icon: '📝' },
    { id: 'grammar',  name: '语法',     color: '#8b5cf6', icon: '📘' },
    { id: 'listening',name: '听力',     color: '#06b6d4', icon: '🎧' },
    { id: 'reading',  name: '阅读',     color: '#f59e0b', icon: '📖' },
    { id: 'writing',  name: '写作',     color: '#10b981', icon: '✍️' },
    { id: 'other',    name: '其他',     color: '#64748b', icon: '📁' }
  ];
  window.LIB_TYPES = TYPE_META;

  var style = getComputedStyle(document.documentElement);
  var accent  = style.getPropertyValue('--accent').trim();
  var accent2 = style.getPropertyValue('--accent2').trim();
  var ink     = style.getPropertyValue('--ink').trim();
  var muted   = style.getPropertyValue('--muted').trim();
  var rule    = style.getPropertyValue('--rule').trim();

  var elType  = document.getElementById('chartType');
  var elStage = document.getElementById('chartStage');

  if (!elType || !elStage) return;

  var chartType  = echarts.init(elType, null, { renderer: 'svg' });
  var chartStage = echarts.init(elStage, null, { renderer: 'svg' });

  window.addEventListener('resize', function () {
    chartType.resize();
    chartStage.resize();
  });

  var monoFont = "'DMMono', 'Consolas', monospace";

  window.renderCharts = function (items) {
    // ---- 类型分布柱状图 ----
    var names  = [];
    var values = [];
    var colors = [];
    TYPE_META.forEach(function (t) {
      names.push(t.name);
      colors.push(t.color);
      values.push(items.filter(function (it) { return it.type === t.id; }).length);
    });

    chartType.setOption({
      animation: false,
      tooltip: {
        trigger: 'axis', appendToBody: true, backgroundColor: 'rgba(30,41,59,0.92)',
        borderWidth: 0, textStyle: { color: '#fff', fontSize: 12 },
        axisPointer: { type: 'shadow', shadowStyle: { color: 'rgba(37,99,235,0.06)' } }
      },
      grid: { left: 8, right: 16, top: 30, bottom: 0, containLabel: true },
      xAxis: {
        type: 'category', data: names,
        axisLine: { lineStyle: { color: rule } },
        axisTick: { show: false },
        axisLabel: { color: muted, fontSize: 11 }
      },
      yAxis: {
        type: 'value', minInterval: 1,
        splitLine: { lineStyle: { color: rule } },
        axisLabel: { color: muted, fontSize: 11 }
      },
      series: [{
        type: 'bar', data: values, barMaxWidth: 36,
        itemStyle: {
          borderRadius: [6, 6, 0, 0],
          color: function (p) { return colors[p.dataIndex]; }
        },
        label: { show: true, position: 'top', color: ink, fontFamily: monoFont, fontSize: 11, fontWeight: 700 }
      }]
    });

    // ---- 学段分布环形图 ----
    var junior = items.filter(function (it) { return it.stage === 'junior'; }).length;
    var senior = items.length - junior;

    chartStage.setOption({
      animation: false,
      tooltip: {
        trigger: 'item', appendToBody: true, backgroundColor: 'rgba(30,41,59,0.92)',
        borderWidth: 0, textStyle: { color: '#fff', fontSize: 12 },
        formatter: '{b}：{c} 份（{d}%）'
      },
      legend: { bottom: 0, itemWidth: 10, itemHeight: 10, textStyle: { color: muted, fontSize: 11 } },
      series: [{
        type: 'pie', radius: ['50%', '74%'], center: ['50%', '44%'],
        avoidLabelOverlap: true,
        itemStyle: { borderColor: '#ffffff', borderWidth: 2 },
        label: {
          show: true, color: ink, fontSize: 12, fontWeight: 600,
          formatter: function (p) { return p.name + '\n' + p.value + ' 份'; },
          lineHeight: 17
        },
        labelLine: { length: 10, length2: 8, lineStyle: { color: rule } },
        data: [
          { value: junior, name: '初中', itemStyle: { color: accent2 } },
          { value: senior, name: '高中', itemStyle: { color: accent } }
        ]
      }]
    });
  };
})();
